version: '3.8'

services:
  server:
    build: .
    ports:
      - "3001:3001"
      
  react-app:
    build: ./src/client/
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://server:3001
