[tool.poetry]
name = "mbajk"
version = "0.1.0"
description = ""
authors = ["Trdin"]
readme = "README.md"
packages = [{include = "poetry_demo"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^2.2.1"
tensorflow-io-gcs-filesystem = "0.27.0"
tensorflow = "~2.10"
numpy = "^1.26.4"
matplotlib = "^3.8.3"
joblib = "^1.3.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"